#TUPLE OPERATIONS
ADD_TUPLE = 0
SUB_TUPLE = 1
MULT_TUPLE = 2
ADD_DIGIT = 3
SUB_DIGIT = 4
MULT_DIGIT = 5

#COLORS
BOARD_GREEN = (29, 171, 72)
LIGHT_BOARD_GREEN = (31, 184, 130)
BACKGROUND_BLUE = (91, 132, 199)
BACKGROUND_GREEN = (113, 168, 145)
BORDER_RED = (120, 16, 28)
TEXT_BOX_ORANGE = (189, 154, 42)
TEXT_BOX_GREEN = (63, 153, 79)

#DIMENSIONS
#Screen
SCREEN_DIMENSIONS = (1280, 720)

#Board
BOARD_EDGE_RADIUS = 7
BOARD_DIMENSIONS = (648, 648)
BOARD_START = (316, 36)
BORDER_THICKNESS = 5
LINE_THICKNESS = 2

#Game Text
TURN_LOCATION = (40, 20)
BLACK_SCORE_LOCATION = (100, 625)
WHITE_SCORE_LOCATION = (1075, 625)

#Pieces
PIECE_OFFSET = 10
PIECE_BORDER_THICKNESS = 2
PIECE_RADIUS = (BOARD_DIMENSIONS[0] / 16) - PIECE_OFFSET
FIRST_PIECE = (BOARD_START[0] + PIECE_RADIUS + PIECE_OFFSET, BOARD_START[1] + PIECE_RADIUS + PIECE_OFFSET)
NEXT_PIECE_OFFSET = PIECE_OFFSET * 2 + PIECE_RADIUS  * 2

#Menu Texts
MENU_TITLE_LOCATION = (SCREEN_DIMENSIONS[0]/2 - 180, SCREEN_DIMENSIONS[1] * .1)
TEXT_BOX_OFFSET = (10, 10)
TITLE_BORDER = BORDER_THICKNESS
TEXT_BOX_CORNER = BOARD_EDGE_RADIUS
OPTION_BORDER = 2
NEXT_BOX_OFFSET = 125

#Specific Text Detail
MIDMENU_TITLE_BOX = (370, 85)
RG_BOX = (225, 65)
RG_LOCATION = (MENU_TITLE_LOCATION[0] + 75, MENU_TITLE_LOCATION[1] + 150)
MIDMENU_BOX = RG_BOX
MIDMENU_LOCATION = (RG_LOCATION[0], RG_LOCATION[1] + NEXT_BOX_OFFSET)
QUIT_BOX = (80, 65)
MM_QUIT_LOCATION = (MIDMENU_LOCATION[0] + 75, MIDMENU_LOCATION[1] + NEXT_BOX_OFFSET)

#TIMING
TIME_IDLE_QUIT = 300 #Seconds
FPS = 100 #Frames Per Second

#STATES
MENU_STATE = 0
CREATE_GAME_STATE = 1
GAME_STATE = 2
MENU_MIDGAME_STATE = 3
RESTART_GAME_STATE = 4
INFO_STATE = 5
CREDITS_STATE = 6
QUIT_STATE = 7

#OTHER
ANTIALIAS_SETTING = True