#TUPLE OPERATIONS
ADD_TUPLE = 0
SUB_TUPLE = 1
MULT_TUPLE = 2
ADD_DIGIT = 3
SUB_DIGIT = 4
MULT_DIGIT = 5

#COLORS
BOARD_GREEN = (29, 171, 72)
LIGHT_BOARD_GREEN = (31, 184, 130)
BACKGROUND_BLUE = (91, 132, 199)
BACKGROUND_GREEN = (113, 168, 145)
BORDER_RED = (120, 16, 28)
TEXT_BOX_ORANGE = (189, 154, 42)
TEXT_BOX_GREEN = (63, 153, 79)

#DIMENSIONS
#Screen
SCREEN_DIMENSIONS = (1280, 720)

#Board
BOARD_EDGE_RADIUS = 7
BOARD_DIMENSIONS = (648, 648)
BOARD_START = (316, 36)
BORDER_THICKNESS = 5
LINE_THICKNESS = 2

#Game Text
TURN_LOCATION = (40, 20)
BLACK_SCORE_LOCATION = (100, 625)
WHITE_SCORE_LOCATION = (1075, 625)

#Pieces
PIECE_OFFSET = 10
PIECE_BORDER_THICKNESS = 2
PIECE_RADIUS = (BOARD_DIMENSIONS[0] / 16) - PIECE_OFFSET
FIRST_PIECE = (BOARD_START[0] + PIECE_RADIUS + PIECE_OFFSET, BOARD_START[1] + PIECE_RADIUS + PIECE_OFFSET)
NEXT_PIECE_OFFSET = PIECE_OFFSET * 2 + PIECE_RADIUS  * 2

#Menu Texts
TEXT_BOX_OFFSET = (10, 10)
TITLE_BORDER = BORDER_THICKNESS
TEXT_BOX_CORNER = BOARD_EDGE_RADIUS
OPTION_BORDER = 2
NEXT_BOX_OFFSET_MM = 125
NEXT_BOX_OFFSET = 100

#Specific Text Detail
MENU_TITLE_LOCATION_MM = (SCREEN_DIMENSIONS[0]/2 - 180, SCREEN_DIMENSIONS[1] * .1)
MIDMENU_TITLE_BOX = (370, 85)
MENU_TITLE_LOCATION = (SCREEN_DIMENSIONS[0]/2 - 118,SCREEN_DIMENSIONS[1] * .1)
MENU_TITLE_BOX = (255, 85)
RG_BOX = (225, 65)
RG_LOCATION = (MENU_TITLE_LOCATION_MM[0] + 75, MENU_TITLE_LOCATION_MM[1] + 150)
MIDMENU_BOX = RG_BOX
MIDMENU_LOCATION = (RG_LOCATION[0], RG_LOCATION[1] + NEXT_BOX_OFFSET_MM)
QUIT_BOX = (80, 65)
MM_QUIT_LOCATION = (MIDMENU_LOCATION[0] + 75, MIDMENU_LOCATION[1] + NEXT_BOX_OFFSET_MM)

NG_BOX = (RG_BOX[0] - 40, RG_BOX[1])
NG_LOCATION = (RG_LOCATION[0] + 25, RG_LOCATION[1])
INFO_BOX = (NG_BOX[0] + 3, NG_BOX[1])
INFO_LOCATION = (NG_LOCATION[0] , NG_LOCATION[1] + NEXT_BOX_OFFSET)
CRED_LOCATION = (INFO_LOCATION[0] + 30, INFO_LOCATION[1] + NEXT_BOX_OFFSET)
CRED_BOX = (125, 65)
QUIT_LOCATION = (CRED_LOCATION[0] + 20, CRED_LOCATION[1] + NEXT_BOX_OFFSET)

INFO_TITLE_LOCATION = (MENU_TITLE_LOCATION[0] - 5, MENU_TITLE_LOCATION[1])
INFO_TITLE_BOX = (MENU_TITLE_BOX[0] + 10, MENU_TITLE_BOX[1])
INFO_TEXT_LOCATION = (INFO_TITLE_LOCATION[0] - 150, INFO_TITLE_LOCATION[1] + 125)

#TIMING
TIME_IDLE_QUIT = 300 #Seconds
FPS = 100 #Frames Per Second

#STATES
MENU_STATE = 0
CREATE_GAME_STATE = 1
GAME_STATE = 2
MENU_MIDGAME_STATE = 3
INFO_STATE = 4
CREDITS_STATE = 5
QUIT_STATE = 6

#OTHER
ANTIALIAS_SETTING = True